spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: fooooo
            clientSecret: fooooo
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    gcp:
      sql:
        enabled: true
        username: ***REMOVED***
        password: fooooo
        database-name: aqhi
        instance-connection-name: fooooo

  sql:
    init:
      mode: always


  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:mem:mydb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    initialization-mode: always

  datasource:
    url: jdbc:google:mysql://fooooo:northamerica-northeast2:fooooo?user=***REMOVED***
    username: ***REMOVED***
    password: fooooo





logging:
  level:
    org:
      springframework:
        security: INFO