spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ***REMOVED***.apps.googleusercontent.com
            clientSecret: ***REMOVED***
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
#      ddl-auto: create



#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://db.dheri.ca:3306/aqhi?user=***REMOVED***
    username: ***REMOVED***
    password: ***REMOVED***

#  datasource:
#    url: jdbc:h2:mem:mydb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    initialization-mode: always

  h2:
    console:
      enabled: true


server:
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    org:
      springframework:
        security: INFO

ca:
  aqhi:
    url: https://api.weather.gc.ca/collections/aqhi-forecasts-realtime/items
    default_location_id: FDQBX
