spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: fooooo
            clientSecret: fooooo
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: validate
      ddl-auto: create

#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://10.0.6.15:3306/aqhi?user=***REMOVED***
    username: ***REMOVED***
    password: ***REMOVED***

#  datasource:
#    url: jdbc:h2:mem:mydb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    initialization-mode: always

  h2:
    console:
      enabled: true


server:
  forward-headers-strategy: FRAMEWORK

logging:
  level:
    org:
      springframework:
        security: INFO